plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose)
}

kotlin {
    jvmToolchain(17)
    wasmJs {
        outputModuleName = 'wasm-app'
        browser {
            commonWebpackConfig {
                outputFileName = 'wasm-app.js'
            }
        }
        binaries.executable()
    }

    sourceSets {
        wasmJsMain {
            kotlin.srcDir('src')
            resources.srcDir('resources')
            dependencies {
                implementation(project(':shared'))
            }
        }
    }
}
