plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose)
}

android {
    namespace = 'hello.world'
    compileSdk = 36

    defaultConfig {
        applicationId = 'hello.world'
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = '1.0'
    }

    sourceSets {
        main {
            manifest.srcFile 'src/AndroidManifest.xml'
            java.srcDirs = ['src']
        }
    }
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation project(':shared')
    implementation libs.activity.compose
}
